(function () {
  const STORAGE_KEY = "gc-language";
  const dictionary = {
    "Original Art in": "Arte original en",\n    "Digital collection": "Colección digital",\n    "Explore Jacarandas": "Ver Jacarandas",\n    "Digital prints from MXN $30 · Bilingual catalogue MXN $150": "Obras descargables desde $30 MXN · Catálogo bilingüe $150 MXN",\n    "Secure payment": "Pago seguro",\n    "Immediate delivery": "Entrega inmediata",\n    "Personal use": "Uso personal",\n    "Payment opens securely on this page through Gumroad.": "El pago se abre de forma segura en esta misma página mediante Gumroad.",\n    "Download your file immediately after your purchase is confirmed.": "Descarga tu archivo inmediatamente después de confirmar la compra.",\n    "Print the artwork for your personal space. Commercial reproduction rights are not included.": "Imprime la obra para tu espacio personal. No incluye derechos de reproducción comercial.",
    "Create inside": "Crea dentro de",
    "a working gallery.": "una galería en activo.",
    "Private 2.5-hour art sessions inside Galería Coahuilteca, with the option of deeper studio experiences in the rural community of Corralejo de Arriba.": "Sesiones artísticas privadas de 2.5 horas dentro de Galería Coahuilteca, con la opción de experiencias más profundas en el estudio rural de Corralejo de Arriba.",
    "From $1,914 MXN per participant. Airbnb pricing may vary slightly by date.": "Desde $1,914 MXN por participante. El precio de Airbnb puede variar ligeramente según la fecha.",
    "Featured Experiences": "Experiencias destacadas",
    "A relaxed creative session with wine, materials and guided painting.": "Una sesión creativa relajada con vino, materiales y pintura guiada.",
    "Draw Your Partner": "Dibuja a tu pareja",
    "A playful guided portrait session for couples, friends or families.": "Una sesión lúdica de retrato guiado para parejas, amistades o familias.",
    "Colors of San Miguel": "Colores de San Miguel",
    "Paint the architecture and colors of San Miguel using your preferred technique.": "Pinta la arquitectura y los colores de San Miguel con la técnica que prefieras.",
    "Airbnb Prices": "Precios en Airbnb",
    "Private 2.5-hour session": "Sesión privada de 2.5 horas",
    "Where the experience takes place": "Dónde se realiza la experiencia",
    "Inside the gallery": "Dentro de la galería",
    "At the rural art studio": "En el estudio rural",
    "Choose your technique": "Elige tu técnica",
    "Gallery techniques": "Técnicas en la galería",
    "Studio techniques": "Técnicas en el estudio",
    "Reserve directly": "Reservar directamente",
    "What happens after you message us": "Qué sucede después de escribirnos",
    "Why does an art gallery carry the name of a nomadic tribe?": "¿Por qué una galería de arte lleva el nombre de un pueblo nómada?",
    "A story about migration, memory, family and art in San Miguel de Allende.": "Una historia sobre migración, memoria, familia y arte en San Miguel de Allende.",
    "Today, we know them as the Coahuiltecans.": "Hoy los conocemos como los coahuiltecos.",
    "We left northern Mexico behind.": "Dejamos atrás el norte de México.",
    "We brought our tools. Our drawings. Our paintings. Our memories.": "Trajimos nuestras herramientas, nuestros dibujos, nuestras pinturas y nuestros recuerdos.",
    "And we arrived in San Miguel de Allende.": "Y llegamos a San Miguel de Allende.",
    "Family. Craft. The need to create.": "La familia. El oficio. La necesidad de crear.",
    "Continue the journey": "Continúa el recorrido",
    "Discover the artwork": "Descubre la obra",
    "Visit the gallery": "Visita la galería",
    "Original Art in San Miguel de Allende": "Arte original en San Miguel de Allende",
    "A working gallery in San Miguel de Allende presenting original paintings, drawings, ceramics, commissioned portraits and private art experiences by local artists.": "Una galería en activo en San Miguel de Allende que presenta pintura, dibujo, cerámica, retratos por encargo y experiencias artísticas privadas de artistas locales.",
    "Conceptual painting exploring movement and human presence.": "Pintura conceptual que explora el movimiento y la presencia humana.",
    "Drawing and painting focused on identity and the body.": "Dibujo y pintura centrados en la identidad y el cuerpo.",
    "Handmade ceramics designed for daily use and collecting.": "Cerámica hecha a mano para el uso cotidiano y el coleccionismo.",
    "Oil portraits created through a traditional Venetian technique, developed slowly through layered painting.": "Retratos al óleo realizados mediante una técnica veneciana tradicional, desarrollados lentamente por capas.",
    "Each portrait is created from photographic references and includes pencil studies as part of the process.": "Cada retrato se crea a partir de referencias fotográficas e incluye estudios a lápiz como parte del proceso.",
    "Only a limited number of portraits are accepted each year.": "Cada año se acepta un número limitado de retratos.",
    "Private art experiences inside a working gallery in San Miguel de Allende.": "Experiencias artísticas privadas dentro de una galería en activo en San Miguel de Allende.",
    "Paint your own Parroquia": "Pinta tu propia Parroquia",
    "Draw your partner": "Dibuja a tu pareja",
    "Watercolor, charcoal, acrylic": "Acuarela, carbón y acrílico",
    "Ask questions by WhatsApp or reserve instantly through Airbnb.": "Pregunta por WhatsApp o reserva al instante mediante Airbnb.",
    "Receive a complimentary printable artwork, plus occasional exhibition invitations and collector notes.": "Recibe una obra imprimible de cortesía, además de invitaciones ocasionales a exposiciones y notas para coleccionistas.",
    "Discover original painting, drawing, ceramics and commissioned portraiture from the artists of Galería Coahuilteca.": "Descubre pintura, dibujo, cerámica y retratos por encargo de los artistas de Galería Coahuilteca.",
    "Enter each artist’s catalogue or commission page to explore the work in greater depth.": "Entra al catálogo o página de encargos de cada artista para conocer su obra con mayor profundidad.",
    "Migration, movement and collective human presence through a graphic, highly recognizable pictorial language.": "Migración, movimiento y presencia humana colectiva mediante un lenguaje pictórico gráfico y reconocible.",
    "Original oil portraits developed through drawing, layered painting and close observation. Private commissions available.": "Retratos originales al óleo desarrollados mediante dibujo, pintura por capas y observación cercana. Encargos privados disponibles.",
    "A hand-built ceramic chess set populated by small character pieces, currently in development at the gallery.": "Un ajedrez de cerámica construido a mano con pequeñas piezas-personaje, actualmente en desarrollo en la galería.",
    "Send a photo and approximate wall dimensions. The gallery can prepare a personal selection of three works for your space.": "Envía una foto y las medidas aproximadas del muro. La galería puede preparar una selección personal de tres obras para tu espacio.",
    "A portrait made to outlive the photograph.": "Un retrato creado para trascender la fotografía.",
    "Commission an original oil portrait by Mexican artist Indhira. Each work is developed slowly through drawing, layered painting and careful observation, creating an image intended to hold presence, memory and character beyond a single photograph.": "Encarga un retrato original al óleo de la artista mexicana Indhira. Cada obra se desarrolla lentamente mediante dibujo, pintura por capas y observación cuidadosa para preservar presencia, memoria y carácter más allá de una sola fotografía.",
    "From photograph to painting.": "De la fotografía a la pintura.",
    "The commission is built as a work of art, not as a photographic copy. Indhira begins by selecting the strongest references, studies the structure of the face, develops the drawing and gradually builds the painting through multiple layers.": "El encargo se construye como una obra de arte, no como una copia fotográfica. Indhira selecciona las mejores referencias, estudia la estructura del rostro, desarrolla el dibujo y construye gradualmente la pintura mediante múltiples capas.",
    "You share who the portrait is for, the feeling you want the work to carry and the space where it may live.": "Compartes para quién es el retrato, la emoción que deseas transmitir y el espacio donde vivirá la obra.",
    "The gallery helps select photographic references with the right light, expression and presence for the painting.": "La galería ayuda a seleccionar referencias fotográficas con la luz, expresión y presencia adecuadas.",
    "The portrait begins with structure, proportion and studies before the final painted layers are developed.": "El retrato comienza con estructura, proporción y estudios antes de desarrollar las capas finales de pintura.",
    "Color, depth and skin are built gradually through a slow layered process until the portrait reaches its final presence.": "El color, la profundidad y la piel se construyen gradualmente por capas hasta que el retrato alcanza su presencia final.",
    "Not simply a likeness. A painting meant to become part of a family’s visual history.": "No es sólo un parecido: es una pintura destinada a formar parte de la historia visual de una familia.",
    "Commission sizes.": "Formatos de encargo.",
    "Choose one of the standard formats below, or contact the gallery to discuss a different size, composition or number of figures.": "Elige uno de los formatos estándar o contacta a la galería para conversar sobre otras medidas, composiciones o número de figuras.",
    "Intimate portrait": "Retrato íntimo",
    "Ideal for one figure.": "Ideal para una figura.",
    "Approx. 3 months": "Aprox. 3 meses",
    "Collector portrait": "Retrato de colección",
    "A larger portrait with greater scale and presence.": "Un retrato de mayor formato, escala y presencia.",
    "Approx. 6 months": "Aprox. 6 meses",
    "Bespoke portrait": "Retrato personalizado",
    "Other dimensions, compositions or multiple figures.": "Otras dimensiones, composiciones o varias figuras.",
    "Format, timeline and price are determined personally with the artist before work begins.": "El formato, plazo y precio se acuerdan personalmente con la artista antes de comenzar.",
    "Price on request": "Precio bajo consulta",
    "What you receive.": "Qué recibirás.",
    "Each finished commission is delivered as an original artwork with gallery documentation and personal support for packing and shipping.": "Cada encargo terminado se entrega como obra original con documentación de la galería y apoyo personal para embalaje y envío.",
    "Original work": "Obra original",
    "An original oil portrait created specifically for the collector.": "Un retrato original al óleo creado especialmente para el coleccionista.",
    "Documentation": "Documentación",
    "Certificate of authenticity and complete technical information for the work.": "Certificado de autenticidad e información técnica completa de la obra.",
    "Private process": "Proceso privado",
    "Direct communication with the gallery throughout the commission.": "Comunicación directa con la galería durante todo el encargo.",
    "Professional packing and worldwide shipping options coordinated by the gallery.": "Embalaje profesional y opciones de envío mundial coordinadas por la galería.",
    "Begin with a photograph.": "Comienza con una fotografía.",
    "Figurative painting, drawing and portraiture exploring identity, memory and the female body.": "Pintura figurativa, dibujo y retrato que exploran identidad, memoria y cuerpo femenino.",
    "Explore Jacarandas or request a private oil portrait commission.": "Explora Jacarandas o solicita un retrato privado al óleo.",
    "A bilingual digital catalogue and downloadable printable artwork from Indhira’s Jacarandas series.": "Catálogo digital bilingüe y obra imprimible descargable de la serie Jacarandas de Indhira.",
    "Request a custom portrait developed in oil paint, created specifically for you or someone you love.": "Solicita un retrato personalizado al óleo, creado especialmente para ti o para alguien importante.",
    "How would you like to connect with the gallery?": "¿Cómo te gustaría comunicarte con la galería?",
    "Whether you are looking for a work to take home, considering a portrait commission or planning a private art experience, we are happy to assist personally.": "Ya sea que busques una obra, consideres encargar un retrato o planees una experiencia artística privada, con gusto te atenderemos personalmente.",
    "A working gallery located in the historic center of San Miguel de Allende.": "Una galería en activo ubicada en el centro histórico de San Miguel de Allende.",
    "Discover original paintings, drawings, ceramics, commissioned portraits and private art experiences in an intimate space where art is created and exhibited.": "Descubre pintura, dibujo, cerámica, retratos por encargo y experiencias artísticas privadas en un espacio íntimo donde el arte se crea y se exhibe.",
    "Ceramic Chess": "Ajedrez de cerámica",
    "The project is currently in development. The gallery is presenting selected studio images while the final set is completed.": "El proyecto está en desarrollo. La galería presenta imágenes seleccionadas del estudio mientras se completa el conjunto final.",
    "Studio process": "Proceso de estudio",
    "Details from the making process reveal the individual modeling, painting and character development behind the set.": "Los detalles del proceso revelan el modelado, la pintura y el desarrollo individual de los personajes del conjunto.",
    "Interested in the finished set?": "¿Te interesa el conjunto terminado?",
    "The ceramic chess set will be presented by the gallery once completed. You can ask to be contacted when final images, dimensions and price are available.": "La galería presentará el ajedrez de cerámica cuando esté terminado. Puedes solicitar que te contactemos cuando estén disponibles las imágenes finales, las dimensiones y el precio.",
    "Home": "Inicio",
    "Shop": "Tienda",
    "Portraits": "Retratos",
    "Experiences": "Experiencias",
    "Cultural agenda": "Agenda cultural",
    "Visit": "Visita",
    "Contact": "Contacto",
    "Available artwork": "Obra disponible",
    "Worldwide shipping": "Envíos a todo el mundo",
    "Artists & work": "Artistas y obra",
    "Explore portfolio →": "Explorar portafolio →",
    "Visit Instagram →": "Visitar Instagram →",
    "COMMISSIONED WORK": "OBRA POR ENCARGO",
    "Portrait Commissions": "Retratos por encargo",
    "by Indhira pintora": "por Indhira pintora",
    "Explore more →": "Explorar más →",
    "Request a Portrait": "Solicitar un retrato",
    "Create inside a working gallery": "Crea dentro de una galería en activo",
    "Ask by WhatsApp": "Preguntar por WhatsApp",
    "Book on Airbnb": "Reservar en Airbnb",
    "Visit us": "Visítanos",
    "Get Directions": "Cómo llegar",
    "Subscribe to our newsletter": "Suscríbete a nuestro boletín",
    "Collect something original.": "Colecciona algo original.",
    "Artists & collections": "Artistas y colecciones",
    "View catalogue →": "Ver catálogo →",
    "Commission a portrait →": "Encargar un retrato →",
    "Preview project →": "Ver proyecto →",
    "Coming soon": "Próximamente",
    "Prefer a private edit?": "¿Prefieres una selección privada?",
    "Request private edit": "Solicitar selección privada",
    "Choose how to connect": "Elige cómo conectar",
    "Printable collection": "Colección imprimible",
    "Open Jacarandas shop": "Abrir tienda Jacarandas",
    "Private commission": "Encargo privado",
    "Oil portrait": "Retrato al óleo",
    "View portrait commissions": "Ver retratos por encargo",
    "Portrait commissions": "Retratos por encargo",
    "Request your portrait": "Solicita tu retrato",
    "The process": "El proceso",
    "Selected works": "Obras seleccionadas",
    "Frequently asked questions": "Preguntas frecuentes",
    "Start your commission": "Inicia tu encargo",
    "Contact the artist": "Contactar a la artista",
    "Jacarandas digital shop": "Tienda digital Jacarandas",
    "Complete collection": "Colección completa",
    "Printable artwork": "Obra imprimible",
    "Purchase / Comprar": "Comprar / Purchase",
    "Price on Gumroad": "Precio en Gumroad",
  "Secure payment": "Pago seguro",
    "Immediate delivery": "Entrega inmediata",
    "Personal use": "Uso personal",
    "About the experience": "Sobre la experiencia",
    "Reserve your experience": "Reserva tu experiencia",
    "Gallery or studio": "Galería o estudio",
    "Cultural agenda in San Miguel de Allende": "Agenda cultural en San Miguel de Allende",
    "Plan your visit": "Planea tu visita",
    "Opening hours": "Horario",
    "Location": "Ubicación",
    "Send us a message": "Envíanos un mensaje",
    "Listen to our story": "Escucha nuestra historia",
    "English": "Inglés",
    "Spanish": "Español",
    "Back to top": "Volver arriba",
    "← Back to shop": "← Volver a la tienda",
    "Portrait commissions · Indhira": "Retratos por encargo · Indhira",
    "View artist profile →": "Ver perfil de la artista →",
    "Original oil painting": "Pintura original al óleo",
    "Traditional layered process": "Proceso tradicional por capas",
    "Certificate of authenticity": "Certificado de autenticidad",
    "Collect": "Colecciona",
    "something original.": "algo original.",
    "Original work · Private assistance · Worldwide shipping": "Obra original · Atención privada · Envíos a todo el mundo",
    "01 · PAINTING": "01 · PINTURA",
    "02 · PORTRAIT COMMISSIONS": "02 · RETRATOS POR ENCARGO",
    "03 · CERAMICS": "03 · CERÁMICA",
    "PAINTING": "PINTURA",
    "PORTRAIT COMMISSIONS": "RETRATOS POR ENCARGO",
    "CERAMICS": "CERÁMICA",
    "Working gallery · San Miguel de Allende": "Galería en activo · San Miguel de Allende",
    "WORKING GALLERY · SAN MIGUEL DE ALLENDE": "GALERÍA EN ACTIVO · SAN MIGUEL DE ALLENDE",
    "Indhira Pintora | Mexican Visual Artist": "Indhira Pintora | Artista Visual Mexicana",
    "Work": "Obra",
    "Biography": "Biografía",
    "Commissions": "Encargos",
    "Menu": "Menú",
    "Painting · Printmaking · Ceramics": "Pintura · Gráfica · Cerámica",
    "Mexican visual artist": "Artista visual mexicana",
    "A figurative practice that reclaims the female body as political territory, a space of memory and a site of resistance.": "Una práctica figurativa que recupera el cuerpo femenino como territorio político, espacio de memoria y lugar de resistencia.",
    "Explore the work": "Conocer la obra",
    "Artistic practice": "Práctica artística",
    "San Miguel de Allende, Mexico": "San Miguel de Allende, México",
    "Indhira develops a figurative practice centered on women’s experiences, the cultural construction of the body, collective memory, and the relationship between identity and territory.": "Indhira desarrolla una obra figurativa centrada en la experiencia de las mujeres, la construcción cultural del cuerpo, la memoria colectiva y la relación entre identidad y territorio.",
    "Her painting recovers historical processes —such as grisaille, glazing, and the Venetian technique— to confront contemporary issues through precise, symbolic, and deeply material images.": "Su pintura recupera procedimientos históricos —como la grisalla, las veladuras y la técnica veneciana— para confrontar problemáticas contemporáneas desde una imagen precisa, simbólica y profundamente material.",
    "A series created using the Venetian technique that examines the female body as a territory contested by the gaze, medicine, fashion, ideology, and power.": "Serie realizada mediante técnica veneciana que examina el cuerpo femenino como un territorio disputado por la mirada, la medicina, la moda, la ideología y el poder.",
    "The project brings together painting, written research, and process memory to construct a visual reflection on autonomy, comfort, disobedience, and resistance.": "El proyecto reúne pintura, investigación escrita y memoria de proceso para construir una reflexión visual sobre autonomía, comodidad, desobediencia y resistencia.",
    "Selected work": "Obra seleccionada",
    "A selection of projects developed through painting, drawing, printmaking, and processes connected with memory and representation.": "Una selección de proyectos desarrollados mediante pintura, dibujo, grabado y procesos vinculados con la memoria y la representación.",
    "Figurative painting and Venetian technique addressing body, autonomy, femininity, and resistance.": "Pintura figurativa y técnica veneciana sobre cuerpo, autonomía, feminidad y resistencia.",
    "Portraits of sisterhood constructed from stories, encounters, and networks of affection among women.": "Retratos de sororidad construidos a partir de historias, encuentros y redes afectivas entre mujeres.",
    "Oil portraits conceived as singular works of art: presence, character, memory, and family continuity.": "Retratos al óleo concebidos como obras irrepetibles: presencia, carácter, memoria y continuidad familiar.",
    "Original work on paper": "Obra original sobre papel",
    "Work on paper recording architecture, urban landscape, migration, community memory, and everyday life.": "Obra sobre papel que registra arquitectura, paisaje urbano, migración, memoria comunitaria y vida cotidiana.",
    "Artist statement": "Declaración de artista",
    "I paint because images can still challenge what culture presents as natural. My work": "Pinto porque la imagen todavía puede disputar aquello que la cultura presenta como natural. Mi obra",
    "reclaims the female body as political territory": "recupera el cuerpo femenino como territorio político",
    ", but also as lived experience, memory, matter, and presence.": ", pero también como experiencia vivida, memoria, materia y presencia.",
    "Indhira is a Mexican visual artist born in Monclova, Coahuila, and based in San Miguel de Allende, Guanajuato. Her practice encompasses painting, drawing, printmaking, and ceramics.": "Indhira es una artista visual mexicana nacida en Monclova, Coahuila, y radicada en San Miguel de Allende, Guanajuato. Su práctica comprende pintura, dibujo, gráfica y cerámica.",
    "She holds a degree in Graphic Design and developed her artistic training for a decade with master Tomás Silvestre at Taller Puerta Morada. She also completed postgraduate studies in Cultural Development at the Autonomous University of Coahuila.": "Es licenciada en Diseño Gráfico y desarrolló durante una década su formación artística con el maestro Tomás Silvestre en el Taller Puerta Morada. También realizó estudios de posgrado en Desarrollo Cultural en la Universidad Autónoma de Coahuila.",
    "She participated in an artistic residency at CONARTE’s Escuela Adolfo Prieto and at the Experimental Printmaking Workshop of Havana. Her work has been exhibited in cultural venues across Coahuila, Guanajuato, and other cities in Mexico.": "Participó en una residencia artística en la Escuela Adolfo Prieto de CONARTE y en el Taller Experimental de Gráfica de La Habana. Su trabajo ha sido exhibido en espacios culturales de Coahuila, Guanajuato y otras ciudades de México.",
    "Jacarandas. Portraits of Sisterhood": "Jacarandas. Retratos de sororidad",
    "Territory of Battle. In Defense of the Female Body": "Territorio de batalla. En defensa del cuerpo femenino",
    ", developed with support from the Program of Stimulus for Artistic Creation and Development.": ", desarrollado con apoyo del Programa de Estímulos a la Creación y Desarrollo Artístico.",
    "Selected training": "Formación seleccionada",
    "Bachelor’s Degree in Graphic Design": "Licenciatura en Diseño Gráfico",
    "Commissioned work": "Obra por encargo",
    "Portraits with permanence": "Retratos con permanencia",
    "Each portrait is developed as a unique work through an initial conversation, image selection, visual proposal, sketches, and execution using traditional oil-painting processes.": "Cada retrato se desarrolla como una obra única, a partir de una conversación inicial, selección de imágenes, propuesta visual, bocetos y ejecución mediante procedimientos tradicionales al óleo.",
    "Request information": "Solicitar información",
    "Acquisitions · Exhibitions · Commissions": "Adquisiciones · Exposiciones · Encargos",
    "To inquire about available work, request a dossier, propose an exhibition, or commission a portrait, contact the artist or Galería Coahuilteca directly.": "Para consultar disponibilidad de obra, solicitar un dossier, proponer una exposición o encargar un retrato, comunícate directamente con la artista o con Galería Coahuilteca.",
    "What to do in": "Qué hacer en",
    "A cultural agenda for visitors. We publish only activities with a date, time, venue, and a source you can open and verify.": "Agenda cultural para visitantes. Publicamos solamente actividades con fecha, hora, sede y una fuente que puedes abrir y comprobar.",
    "Create art inside a gallery": "Crea arte dentro de una galería",
    "A private 2.5-hour experience at Galería Coahuilteca, just steps away from events in the historic center.": "Una experiencia privada de 2.5 horas en Galería Coahuilteca, a unos pasos de los eventos del Centro.",
    "Manuel Álvarez Bravo: Collaborations": "Manuel Álvarez Bravo: Colaboraciones",
    "Instituto Allende House Museum · Free admission · Exhibition through November 9": "Instituto Allende Casa Museo · Entrada libre · exposición hasta el 9 de noviembre",
    "Music": "Música",
    "Mexican Music · Operísima México": "Música Mexicana · Operísima México",
    "Casa Europa México · San Francisco 23, Centro · Tickets required": "Casa Europa México · San Francisco 23, Centro · Boletos requeridos",
    "Traditional Mexican music": "Música tradicional mexicana",
    "Courtyard · Biblioteca Pública A.C.": "Patio · Biblioteca Pública A.C.",
    "Music · Benefit": "Música · Beneficio",
    "Yambu Gallery · Las Palmas 11, San Antonio · Tickets required": "Yambu Gallery · Las Palmas 11, San Antonio · Boletos requeridos",
    "Music · Dance": "Música · Danza",
    "Casa de Sierra Nevada · Hospicio 35 · Reservation required": "Casa de Sierra Nevada · Hospicio 35 · Reservación requerida",
    "El Sindicato · Recreo 4 · Screening and conversation": "El Sindicato · Recreo 4 · Proyección y conversación",
    "Artist creating in situ · Saturday": "Artista creando in situ · Sábado",
    "Galería Coahuilteca · Tenerías at Codo · Watch the artistic process inside the gallery": "Galería Coahuilteca · Tenerías esquina Codo · Observa el proceso artístico dentro de la galería",
    "Location and visit ↗": "Ubicación y visita ↗",
    "Tradition": "Tradición",
    "Defense of Chapultepec Castle and sacrifice of the Niños Héroes": "Defensa del Castillo de Chapultepec y sacrificio de los Niños Héroes",
    "Artist creating in situ · Sunday": "Artista creando in situ · Domingo",
    "Opera · Tradition": "Ópera · Tradición",
    "Mexican celebration benefiting Operísima México": "Fiesta mexicana a beneficio de Operísima México",
    "Viñedos Patria · Opera, mariachi, and equestrian show · Reservations": "Viñedos Patria · Ópera, mariachi y espectáculo ecuestre · Reservaciones",
    "View information and reservations ↗": "Ver información y reservas ↗",
    "Mexican music": "Música mexicana",
    "Independence Day celebration · Disidente Norteño and Grupo Malo": "Fiesta del Grito · Disidente Norteño y Grupo Malo",
    "Create mojigangas with reed and cardboard": "Crear mojigangas con carrizo y cartón",
    "Live music": "Música en vivo",
    "Andy Aristizábal at La Baha": "Andy Aristizábal en La Baha",
    "Cinema and analysis: Serpent and the Rainbow": "Cine y análisis: Serpent and the Rainbow",
    "Music · Gospel": "Música · Gospel",
    "Teatro Santa Ana · Biblioteca Pública · Tickets required": "Teatro Santa Ana · Biblioteca Pública · Boletos requeridos",
    "Rubén Barrera: Mexican music of the 20th century": "Rubén Barrera: Música mexicana del siglo XX",
    "Classical music": "Música clásica",
    "Templo de la Tercera Orden · Presented by Casa Europa México · Tickets": "Templo de la Tercera Orden · Presentado por Casa Europa México · Boletos",
    "Michael Parks · An evening with the music of Bach": "Michael Parks · Una noche con la música de Bach",
    "Templo de la Tercera Orden · Presented by Casa Europa México · Free admission": "Templo de la Tercera Orden · Presentado por Casa Europa México · Entrada libre",
    "View official information ↗": "Ver información oficial ↗",
    "The Prince of Nanawa · Part One": "El príncipe de Nanawa · Primera parte",
    "Miguel Omaña: Emotions of Latin America": "Miguel Omaña: Emociones de Latinoamérica",
    "Guanajuato and participating venues · International program of music, theater, dance, and visual arts": "Guanajuato y sedes participantes · Programa internacional de música, teatro, danza y artes visuales",
    "Art Walk · Fábrica La Aurora": "Art Walk · Fábrica La Aurora",
    "Fábrica La Aurora · Tour of galleries and studios": "Fábrica La Aurora · Recorrido por galerías y estudios",
    "TEDxSanMiguelDeAllende · Threshold of the Future": "TEDxSanMiguelDeAllende · Umbral del Futuro",
    "Buy tickets ↗": "Comprar boletos ↗",
    "Schedule to be confirmed": "Horario por confirmar",
    "Casa Europa México · Anna Komusiński, cello · Joanna Sochacka, piano": "Casa Europa México · Anna Komusiński, violonchelo · Joanna Sochacka, piano",
    "Independent agenda curated by Galería Coahuilteca · Tenerías at Codo · Centro · San Miguel de Allende": "Agenda independiente curada por Galería Coahuilteca · Tenerías esq. Codo · Centro · San Miguel de Allende",
    "View catalogue": "📖 Ver catálogo",
    "Subscribe to our newsletter and receive a printable artwork as a gift.": "Suscríbete a nuestro boletín y recibe de regalo una obra imprimible.",
    "Audio in Spanish": "Audio en Español",
    "Purchase": "Comprar",
    "English + Spanish": "Inglés + Español",
    "Payment opens on this page through Gumroad’s secure system.": "El pago se abre sobre esta misma página mediante el sistema seguro de Gumroad.",
    "The file will be available for immediate download after the purchase is confirmed.": "El archivo estará disponible para descarga inmediatamente después de confirmar la compra.",
    "You may print the artwork for your personal space. Commercial reproduction rights are not included.": "Puedes imprimir la obra para tu espacio personal. No incluye derechos de reproducción comercial.",
    "Woman Facing the Wall": "Mujer frente al muro",
    "Young Woman at the Barricade": "Joven frente a la barricada",
    "Free": "Libres",
    "Collective Embrace": "Abrazo colectivo",
    "To Be Free or Not to Be": "Ser libre o no ser",
    "Long Live the Vulva": "Viva la vulva",
    "Women Raising Their Voices": "Mujeres alzando la voz",
    "Not One Woman Less": "Ni una menos",
    "Girl at the March": "Niña en la marcha",
    "Women’s March": "Marcha de mujeres",
    "They Took So Much from Us That They Took Away Our Fear": "Nos quitaron tanto que nos quitaron el miedo",
    "I March Because I Am Alive, but I Don’t Know for How Long": "Me marcho porque estoy viva, pero no sé hasta cuándo",
    "Bandanas and Raised Fists": "Pañuelos y puños en alto",
    "I Am Neither Hysterical nor Menstruating": "Ni soy histérica ni estoy menstruando",
    "Abortion Is Also Taking Responsibility": "Abortar también es hacerse cargo",
    "Women Occupying Space": "Mujeres ocupando el espacio",
    "We Are the Cry of Those No Longer Here": "Somos el grito de las que ya no están",
    "International Women’s Day 2020": "8M 2020",
    "Digital products are for personal use only. Due to the nature of downloadable files, purchases are final. Prices in Mexican pesos are approximate; the final amount will depend on the exchange rate applied during payment.": "Digital products are for personal use only. Due to the nature of downloadable files, purchases are final. Los precios en pesos son aproximados; el importe final dependerá del tipo de cambio aplicado durante el pago.",
    "Galería Coahuilteca · San Miguel de Allende · Mexico": "Galería Coahuilteca · San Miguel de Allende · México",
  };

  /* AUDIT_COMPLETE_TRANSLATIONS */
  Object.assign(dictionary, {
  "· Worldwide shipping ·": "· Envíos a todo el mundo ·",
  "A gift from the gallery": "Un regalo de la galería",
  "Collectors · Press · Commissions · Private appointments": "Coleccionistas · Prensa · Encargos · Citas privadas",
  "Limited commissions each year · Worldwide shipping · Private guidance from the gallery": "Encargos limitados cada año · Envíos a todo el mundo · Atención privada de la galería",
  "Conversation": "Conversación",
  "References": "Referencias",
  "Drawing": "Dibujo",
  "Painting": "Pintura",
  "DEVELOPING THE IMAGE": "DESARROLLO DE LA IMAGEN",
  "AN EARLIER STAGE": "UNA ETAPA ANTERIOR",
  "50% deposit to begin": "50% de anticipo para comenzar",
  "50% before delivery": "50% antes de la entrega",
  "Painted detail · Layer, color and gesture": "Detalle pictórico · Capa, color y gesto",
  "The artist at work · San Miguel de Allende": "La artista trabajando · San Miguel de Allende",
  "Delivery": "Entrega",
  "Send the gallery one or two reference images and the approximate size you are considering. If you are in San Miguel de Allende, Indhira can also photograph you personally for the portrait once the commission is confirmed. We will guide you through each step personally.": "Envía a la galería una o dos imágenes de referencia y el tamaño aproximado que estás considerando. Si estás en San Miguel de Allende, Indhira también puede fotografiarte personalmente una vez confirmado el encargo. Te guiaremos personalmente en cada paso.",
  "Explore more work from Galería Coahuilteca": "Explora más obra de Galería Coahuilteca",
  "Portrait commissions by Indhira": "Retratos por encargo de Indhira",
  "Art Experiences": "Experiencias artísticas",
  "Paint & Wine": "Pintura y vino",
  "1 participant": "1 participante",
  "2 participants": "2 participantes",
  "3 participants": "3 participantes",
  "4 participants": "4 participantes",
  "Private group rate · 15% group discount": "Tarifa de grupo privado · 15% de descuento grupal",
  "15% group discount": "15% de descuento grupal",
  "Best group rate · 25% group discount": "Mejor tarifa grupal · 25% de descuento",
  "Airbnb prices may vary slightly by date. USD amounts are approximate and update daily using an institutional reference exchange rate.": "Los precios de Airbnb pueden variar ligeramente según la fecha. Los importes en USD son aproximados y se actualizan diariamente con un tipo de cambio institucional de referencia.",
  "All materials are included, along with step-by-step guidance by a professional local artist with over 20 years of experience. Accompanied by Chiapas coffee and a curated selection of light refreshments. Each participant completes and takes home their own artwork, and also receives a small original piece from the gallery, presented in a custom Galería Coahuilteca tote bag.": "Todos los materiales están incluidos, junto con la guía paso a paso de una artista local profesional con más de 20 años de experiencia. Se acompaña con café de Chiapas y una selección de refrigerios ligeros. Cada participante termina y se lleva su propia obra, además de recibir una pequeña pieza original de la galería en una bolsa de Galería Coahuilteca.",
  "Most drawing and painting sessions take place inside Galería Coahuilteca, in the historic center of San Miguel de Allende.": "La mayoría de las sesiones de dibujo y pintura se realizan dentro de Galería Coahuilteca, en el centro histórico de San Miguel de Allende.",
  "Best for graphite, watercolor, charcoal, acrylic, oil pastels, soft pastels and clean mixed media.": "Ideal para grafito, acuarela, carbón, acrílico, pastel al óleo, pastel seco y técnicas mixtas limpias.",
  "Central, easy, walkable and ideal for visitors who want a beautiful creative experience without leaving downtown.": "Céntrica, accesible a pie e ideal para visitantes que desean una bella experiencia creativa sin salir del centro.",
  "Get directions": "Cómo llegar",
  "Open gallery map →": "Abrir mapa de la galería →",
  "Messier and more material-based techniques take place at the private studio in Corralejo de Arriba, a rural community about 15 minutes from the gallery and del centro de San Miguel.": "Las técnicas con más materiales se realizan en el estudio privado de Corralejo de Arriba, una comunidad rural a unos 15 minutos de la galería y del centro de San Miguel.",
  "Messier and more material-based techniques take place at the private studio in Corralejo de Arriba, a rural community about 15 minutes from the gallery and downtown San Miguel.": "Las técnicas con más materiales se realizan en el estudio privado de Corralejo de Arriba, una comunidad rural a unos 15 minutos de la galería y del centro de San Miguel.",
  "Best for oil painting, ceramics and printmaking. This option offers a slower, deeper and more immersive artistic experience surrounded by a quieter landscape.": "Ideal para óleo, cerámica y grabado. Esta opción ofrece una experiencia artística más pausada, profunda e inmersiva en un paisaje tranquilo.",
  "Transportation is not included, but the location opens easily in Google Maps.": "El transporte no está incluido, pero la ubicación se abre fácilmente en Google Maps.",
  "Open studio map →": "Abrir mapa del estudio →",
  "Graphite": "Grafito",
  "Charcoal": "Carbón",
  "Watercolor": "Acuarela",
  "Acrylic": "Acrílico",
  "Oil pastels": "Pastel al óleo",
  "Soft pastels": "Pastel seco",
  "Clean mixed media": "Técnicas mixtas limpias",
  "Oil painting": "Pintura al óleo",
  "Ceramics": "Cerámica",
  "Printmaking": "Grabado",
  "Longer material-based processes": "Procesos de materiales más prolongados",
  "Booking": "Reservaciones",
  "You can book through Airbnb, or request a custom private session directly with Galería Coahuilteca by WhatsApp. For direct inquiries, send your preferred date, time, number of guests and chosen experience.": "Puedes reservar mediante Airbnb o solicitar por WhatsApp una sesión privada personalizada directamente con Galería Coahuilteca. Envía la fecha, hora, número de participantes y experiencia elegida.",
  "Best option for gallery sessions. Airbnb bookings are available only for experiences held at Galería Coahuilteca.": "La mejor opción para sesiones en la galería. Las reservas de Airbnb están disponibles únicamente para experiencias realizadas en Galería Coahuilteca.",
  "For rural studio sessions — including pouring, ceramics, printmaking and oil painting — please contact us directly to confirm available dates.": "Para sesiones en el estudio rural —incluidos pouring, cerámica, grabado y óleo— contáctanos directamente para confirmar fechas disponibles.",
  "The same participant prices apply.": "Se aplican los mismos precios por participante.",
  "Open Airbnb": "Abrir Airbnb",
  "Choose this option for rural studio sessions, custom dates, private groups, couples or families.": "Elige esta opción para sesiones en el estudio rural, fechas personalizadas, grupos privados, parejas o familias.",
  "Studio techniques include pouring, ceramics, printmaking and oil painting. The same participant prices apply; availability must be confirmed directly with the gallery.": "Las técnicas de estudio incluyen pouring, cerámica, grabado y óleo. Se aplican los mismos precios por participante; la disponibilidad debe confirmarse directamente con la galería.",
  "We will send available times, prices and payment options. For direct reservations, PayPal is recommended for international visitors and bank transfer for clients in Mexico. Airbnb remains available for guests who prefer platform booking.": "Enviaremos horarios disponibles, precios y opciones de pago. Para reservas directas recomendamos PayPal a visitantes internacionales y transferencia bancaria a clientes en México. Airbnb sigue disponible para quienes prefieren reservar en la plataforma.",
  "Art Gallery": "Galería de arte",
  "Hours": "Horario",
  "Open daily": "Abierto todos los días",
  "Available artwork · Reservations · Commissions": "Obra disponible · Reservaciones · Encargos",
  "Email": "Correo electrónico",
  "Newsletter": "Boletín",
  "Signup for news and special offers!": "¡Suscríbete para recibir noticias y ofertas especiales!",
  "Sign up for news and special offers!": "¡Suscríbete para recibir noticias y ofertas especiales!",
  "Available Works · Galería Coahuilteca": "Obra disponible · Galería Coahuilteca",
  "Original paintings exploring migration, movement and collective human presence. Prices and dimensions appear on each catalogue sheet.": "Pinturas originales que exploran la migración, el movimiento y la presencia humana colectiva. Los precios y medidas aparecen en cada ficha del catálogo.",
  "Original work · San Miguel de Allende · Mexico & USA shipping · International quotes available": "Obra original · San Miguel de Allende · Envíos a México y EE. UU. · Cotizaciones internacionales disponibles",
  "53 works available in catalogue": "53 obras disponibles en el catálogo",
  "Shipping is shown with each work. Canvas works are carefully protected and shipped rolled, without wooden stretcher bars. Works on cotton paper are shipped carefully protected. Other destinations, stretched-canvas shipping and framed shipping are quoted individually.": "El envío se indica en cada obra. Los lienzos se protegen y envían enrollados, sin bastidor. Las obras sobre papel de algodón se envían protegidas. Otros destinos y los envíos con bastidor o marco se cotizan individualmente.",
  "Looking for something made for your space?": "¿Buscas una obra creada para tu espacio?",
  "Fermigrante can create an original work in custom dimensions and a color palette selected for your space. Tell us the size and colors you have in mind.": "Fermigrante puede crear una obra original en medidas especiales y con una paleta elegida para tu espacio. Cuéntanos qué tamaño y colores tienes en mente.",
  "Request a custom work": "Solicitar una obra personalizada",
  "Need assistance?": "¿Necesitas ayuda?",
  "Send the gallery the work reference and your destination. We will confirm availability, final shipping and payment options.": "Envía a la galería la referencia de la obra y tu destino. Confirmaremos disponibilidad, envío final y opciones de pago.",
  "Contact the gallery": "Contactar a la galería",
  "Fermigrante · Available works": "Fermigrante · Obras disponibles",
  "Edd · Ceramic Chess · Preview": "Edd · Ajedrez de cerámica · Avance",
  "Galería Coahuilteca · Ceramics": "Galería Coahuilteca · Cerámica",
  "Ceramic Chess — a hand-built chess set composed of individually modeled characters. Each figure is made by hand, giving the set the character of a small sculptural world rather than a conventional game object.": "Ajedrez de cerámica: un conjunto construido a mano con personajes modelados individualmente. Cada figura está hecha a mano, lo que le da el carácter de un pequeño mundo escultórico.",
  "Hand-built ceramic · Unique project · San Miguel de Allende": "Cerámica hecha a mano · Proyecto único · San Miguel de Allende",
  "Ceramic Chess · Work in progress": "Ajedrez de cerámica · Obra en proceso",
  "Hand-modeled characters": "Personajes modelados a mano",
  "Individually modeled pieces": "Piezas modeladas individualmente",
  "Notify me": "Avísame",
  "Edd · Ceramic Chess · Coming soon": "Edd · Ajedrez de cerámica · Próximamente",
  "Indhira · Printable collection": "Indhira · Colección imprimible",
  "A collection about women, memory, resistance and presence. Discover the complete bilingual catalogue or collect an individual printable artwork.": "Una colección sobre mujeres, memoria, resistencia y presencia. Descubre el catálogo bilingüe completo o adquiere una obra imprimible individual.",
  "High-resolution digital files for personal printing. Secure purchase and immediate digital delivery after payment.": "Archivos digitales de alta resolución para impresión personal. Compra segura y entrega digital inmediata después del pago.",
  "Jacarandas — Bilingual catalogue": "Jacarandas — Catálogo bilingüe",
  "From MXN $99": "Desde MXN $99",
  "Choose a higher amount if you wish": "Puedes elegir pagar más",
  "Complete bilingual digital catalogue of the Jacarandas series.": "Catálogo digital bilingüe con la serie completa Jacarandas.",
  "Digital PDF": "PDF digital",
  "English + Español": "Inglés + Español",
  "Secure payment processed by Gumroad · Immediate download": "Pago seguro procesado por Gumroad · Descarga inmediata",
  "Printable artwork · 01": "Obra imprimible · 01",
  "Printable artwork · 02": "Obra imprimible · 02",
  "Printable artwork · 03": "Obra imprimible · 03",
  "Printable artwork · 04": "Obra imprimible · 04",
  "Printable artwork · 05": "Obra imprimible · 05",
  "Printable artwork · 06": "Obra imprimible · 06",
  "Printable artwork · 07": "Obra imprimible · 07",
  "Printable artwork · 08": "Obra imprimible · 08",
  "Printable artwork · 09": "Obra imprimible · 09",
  "Printable artwork · 10": "Obra imprimible · 10",
  "Printable artwork · 11": "Obra imprimible · 11",
  "Printable artwork · 12": "Obra imprimible · 12",
  "Printable artwork · 13": "Obra imprimible · 13",
  "Printable artwork · 14": "Obra imprimible · 14",
  "Printable artwork · 15": "Obra imprimible · 15",
  "Printable artwork · 16": "Obra imprimible · 16",
  "Printable artwork · 17": "Obra imprimible · 17",
  "Printable artwork · 18": "Obra imprimible · 18",
  "Printable artwork · 19": "Obra imprimible · 19",
  "Printable artwork · 20": "Obra imprimible · 20",
  "Printable artwork · 21": "Obra imprimible · 21",
  "Printable artwork · 22": "Obra imprimible · 22",
  "Printable artwork · 23": "Obra imprimible · 23",
  "Printable artwork · 24": "Obra imprimible · 24",
  "Printable artwork · 25": "Obra imprimible · 25",
  "Printable artwork · 26": "Obra imprimible · 26",
  "Printable artwork · 27": "Obra imprimible · 27",
  "Printable artwork · 28": "Obra imprimible · 28",
  "Printable artwork · 29": "Obra imprimible · 29",
  "Printable artwork · 30": "Obra imprimible · 30",
  "Printable artwork · 31": "Obra imprimible · 31",
  "Woman Facing the Wall — high-resolution printable artwork.": "Mujer frente al muro — obra imprimible de alta resolución.",
  "May Our Voice Become a Hurricane — high-resolution printable artwork.": "Que nuestra voz sea un huracán — obra imprimible de alta resolución.",
  "Young Women Marching — high-resolution printable artwork.": "Jóvenes en marcha — obra imprimible de alta resolución.",
  "Woman and Daughter Defending Their Rights — high-resolution printable artwork.": "Mujer e hija defendiendo sus derechos — obra imprimible de alta resolución.",
  "Woman with a Megaphone — high-resolution printable artwork.": "Mujer con megáfono — obra imprimible de alta resolución.",
  "Woman with Her Face Covered — high-resolution printable artwork.": "Mujer con el rostro cubierto — obra imprimible de alta resolución.",
  "Raised Fist — high-resolution printable artwork.": "Puño en alto — obra imprimible de alta resolución.",
  "I Am Tired of Being Afraid, I Want to Be Free — high-resolution printable artwork.": "Estoy harta de tener miedo, quiero ser libre — obra imprimible de alta resolución.",
  "Sorry for the Inconvenience, We Are Being Killed — high-resolution printable artwork.": "Disculpe las molestias, nos están matando — obra imprimible de alta resolución.",
  "OKUPA — high-resolution printable artwork.": "OKUPA — obra imprimible de alta resolución.",
  "Two Women with Green Scarves — high-resolution printable artwork.": "Dos mujeres con pañuelos verdes — obra imprimible de alta resolución.",
  "El aborto es nuestro derecho — high-resolution printable artwork.": "El aborto es nuestro derecho — obra imprimible de alta resolución.",
  "Digital products are for personal use only. Downloadable purchases are final. Prices are shown in the checkout currency; your bank may apply its exchange rate.": "Los productos digitales son sólo para uso personal. Las compras de archivos descargables son definitivas. Los precios se muestran en la moneda del pago; tu banco puede aplicar su tipo de cambio.",
  "Printable PDF": "PDF imprimible",
  "High resolution": "Alta resolución",
  "Young Woman at the Barricade — high-resolution printable artwork.": "Joven frente a la barricada — obra imprimible de alta resolución.",
  "Free — high-resolution printable artwork from Jacarandas.": "Libres — obra imprimible de alta resolución de Jacarandas.",
  "Collective Embrace — high-resolution printable artwork.": "Abrazo colectivo — obra imprimible de alta resolución.",
  "To Be Free or Not to Be — high-resolution printable artwork.": "Ser libre o no ser — obra imprimible de alta resolución.",
  "Long Live the Vulva — feminism, equality and freedom.": "Viva la vulva — feminismo, igualdad y libertad.",
  "Women Raising Their Voices — high-resolution printable artwork.": "Mujeres alzando la voz — obra imprimible de alta resolución.",
  "Not One Woman Less — high-resolution printable artwork.": "Ni una menos — obra imprimible de alta resolución.",
  "The Future Is Female": "El futuro es femenino",
  "A high-resolution printable artwork from the Jacarandas series.": "Obra imprimible de alta resolución de la serie Jacarandas.",
  "Digital products are for personal use only. Due to the nature of downloadable files, purchases are final. Los precios en pesos son aproximados; el importe final dependerá del tipo de cambio aplicado durante el pago.": "Los productos digitales son sólo para uso personal. Por la naturaleza de los archivos descargables, las compras son definitivas. Los precios en pesos son aproximados; el importe final dependerá del tipo de cambio aplicado durante el pago.",
  "Printable art · Secure payment · Immediate delivery": "Arte imprimible · Pago seguro · Entrega inmediata",
  "Artist · Galería Coahuilteca": "Artista · Galería Coahuilteca",
  "Worldwide shipping · Private commissions": "Envíos a todo el mundo · Encargos privados",
  "The story behind our name": "La historia detrás de nuestro nombre",
  "Listen to the story": "Escucha la historia",
  "Audio in English": "Audio en inglés",
  "Long before states existed. Long before borders existed. Long before there were maps.": "Mucho antes de que existieran los estados. Mucho antes de que existieran las fronteras. Mucho antes de que hubiera mapas.",
  "Small human groups moved through the territories we now call Coahuila, Nuevo León, Tamaulipas and South Texas.": "Pequeños grupos humanos recorrían los territorios que hoy llamamos Coahuila, Nuevo León, Tamaulipas y el sur de Texas.",
  "Their history traveled with them. It lived in memory. In stories. In people.": "Su historia viajaba con ellos. Vivía en la memoria. En los relatos. En las personas.",
  "When the time came to name this gallery, we thought of those ancient travelers.": "Cuando llegó el momento de nombrar esta galería, pensamos en aquellos antiguos viajeros.",
  "Perhaps because we, too, had begun our own journey. We had changed cities, built a new life and learned to look at a different landscape.": "Quizá porque nosotros también habíamos comenzado nuestro propio viaje. Habíamos cambiado de ciudad, construido una nueva vida y aprendido a mirar un paisaje distinto.",
  "Yet something remained intact.": "Sin embargo, algo permaneció intacto.",
  "Galería Coahuilteca was born from that experience. From understanding that one can travel great distances and still preserve what gives them identity.": "Galería Coahuilteca nació de esa experiencia: de comprender que podemos recorrer grandes distancias y conservar aquello que nos da identidad.",
  "Because memory also travels. And some stories find new ways to keep being told.": "Porque la memoria también viaja. Y algunas historias encuentran nuevas maneras de seguir siendo contadas.",
  "Now that you know the origin of our name, we invite you to discover the artwork, visit the gallery or write to us.": "Ahora que conoces el origen de nuestro nombre, te invitamos a descubrir la obra, visitar la galería o escribirnos.",
  "Write to us": "Escríbenos",
  "Private gallery list": "Lista privada de la galería",
  "Stay close": "Mantente cerca",
  "to the art": "del arte",
  "Receive exhibition invitations and important news from Galería Coahuilteca.": "Recibe invitaciones a exposiciones y noticias importantes de Galería Coahuilteca.",
  "Email address": "Correo electrónico",
  "Subscribe": "Suscribirme",
  "Continue with WhatsApp": "Continuar por WhatsApp",
  "Choose one option. Occasional messages only. You can unsubscribe at any time.": "Elige una opción. Sólo enviaremos mensajes ocasionales. Puedes cancelar tu suscripción en cualquier momento.",
  "Visit the gallery website →": "Visitar el sitio de la galería →"
});

  const reverseDictionary = Object.fromEntries(
    Object.entries(dictionary).map(([english, spanish]) => [spanish, english])
  );
  const originals = new WeakMap();
  const originalAttributes = new WeakMap();
  let currentLanguage = "en";
  let translationScheduled = false;

  function translateTextNode(node, language) {
    if (!originals.has(node)) originals.set(node, node.nodeValue);
    const original = originals.get(node);
    const trimmed = original.trim().replace(/\s+/g, " ");
    const translated = language === "es"
      ? dictionary[trimmed]
      : reverseDictionary[trimmed];
    const leading = original.match(/^\s*/)[0];
    const trailing = original.match(/\s*$/)[0];
    node.nodeValue = leading + (translated || trimmed) + trailing;
  }

  function applyLanguage(language) {
    currentLanguage = language;
    document.documentElement.lang = language;
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
      acceptNode(node) {
        const parent = node.parentElement;
        if (!parent || /^(SCRIPT|STYLE|NOSCRIPT)$/.test(parent.tagName)) return NodeFilter.FILTER_REJECT;
        return node.nodeValue.trim() ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
      }
    });
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(node => translateTextNode(node, language));
    document.querySelectorAll("input[placeholder], button[aria-label]").forEach(element => {
      if (!originalAttributes.has(element)) {
        originalAttributes.set(element, {
          placeholder: element.getAttribute("placeholder"),
          ariaLabel: element.getAttribute("aria-label")
        });
      }
      const source = originalAttributes.get(element);
      ["placeholder", "ariaLabel"].forEach(key => {
        const original = source[key];
        if (!original) return;
        const translated = language === "es" ? dictionary[original] : reverseDictionary[original];
        const attribute = key === "ariaLabel" ? "aria-label" : "placeholder";
        element.setAttribute(attribute, translated || original);
      });
    });
    document.querySelectorAll(".gc-language-button").forEach(button => {
      const active = button.dataset.language === language;
      button.classList.toggle("is-active", active);
      button.setAttribute("aria-pressed", String(active));
    });
    try { localStorage.setItem(STORAGE_KEY, language); } catch (error) {}
  }

  function buildSelector() {
    if (document.querySelector(".gc-language-switch")) return;
    const host = document.querySelector("header nav") || document.body;
    const selector = document.createElement("div");
    selector.className = "gc-language-switch";
    selector.classList.add(host.tagName === "NAV" ? "gc-language-under-menu" : "gc-language-floating");
    selector.setAttribute("aria-label", "Idioma / Language");
    selector.innerHTML = '<button type="button" class="gc-language-button" data-language="es">ES</button><span aria-hidden="true">/</span><button type="button" class="gc-language-button" data-language="en">EN</button>';
    host.appendChild(selector);
    selector.querySelectorAll("button").forEach(button => {
      button.addEventListener("click", () => applyLanguage(button.dataset.language));
    });
  }

  const style = document.createElement("style");
  style.textContent = '.gc-language-switch{display:flex;align-items:center;gap:6px;font:700 11px/1 Arial,sans-serif;letter-spacing:.12em;color:#555;white-space:nowrap;z-index:1001}.gc-language-under-menu{position:absolute;right:0;top:calc(100% + 9px);padding:5px 0}.gc-language-floating{position:fixed;right:20px;top:20px;padding:10px 12px;background:rgba(255,255,255,.94);border:1px solid rgba(0,0,0,.12);border-radius:999px;box-shadow:0 6px 20px rgba(0,0,0,.10);backdrop-filter:blur(8px)}.gc-language-button{border:0;background:transparent;color:inherit;padding:6px 2px;cursor:pointer;opacity:.45}.gc-language-button.is-active{opacity:1;text-decoration:underline;text-underline-offset:4px}@media(max-width:800px){.gc-language-floating{right:14px;bottom:14px;padding:9px 11px}}';
  document.head.appendChild(style);
  const nav = document.querySelector("header nav");
  if (nav) nav.style.position = "relative";

  function start() {
    buildSelector();
    let language = "";
    try { language = localStorage.getItem(STORAGE_KEY) || ""; } catch (error) {}
    if (!language) language = navigator.language.toLowerCase().startsWith("es") ? "es" : "en";
    applyLanguage(language);
    const observer = new MutationObserver(mutations => {
      if (!mutations.some(mutation => mutation.addedNodes.length)) return;
      if (translationScheduled) return;
      translationScheduled = true;
      setTimeout(() => {
        translationScheduled = false;
        applyLanguage(currentLanguage);
      }, 50);
    });
    observer.observe(document.body, {childList:true, subtree:true});
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", start);
  else start();
})();
