(function () {
  const STORAGE_KEY = "gc-language";
  const dictionary = {
    "Original Art in": "Arte original en",
    "Create inside": "Crea dentro de",
    "a working gallery.": "una galería en activo.",
    "Private 2.5-hour art sessions inside Galería Coahuilteca, with the option of deeper studio experiences in the rural community of Corralejo de Arriba.": "Sesiones artísticas privadas de 2.5 horas dentro de Galería Coahuilteca, con la opción de experiencias más profundas en el estudio rural de Corralejo de Arriba.",
    "From $1,914 MXN per participant. Airbnb pricing may vary slightly by date.": "Desde $1,914 MXN por participante. El precio de Airbnb puede variar ligeramente según la fecha.",
    "Featured Experiences": "Experiencias destacadas",
    "A relaxed creative session with wine, materials and guided painting.": "Una sesión creativa relajada con vino, materiales y pintura guiada.",
    "Draw Your Partner": "Dibuja a tu pareja",
    "A playful guided portrait session for couples, friends or families.": "Una sesión lúdica de retrato guiado para parejas, amistades o familias.",
    "Colors of San Miguel": "Colores de San Miguel",
    "Paint the architecture and colors of San Miguel using your preferred technique.": "Pinta la arquitectura y los colores de San Miguel con la técnica que prefieras.",
    "Airbnb Prices": "Precios en Airbnb",
    "Private 2.5-hour session": "Sesión privada de 2.5 horas",
    "Where the experience takes place": "Dónde se realiza la experiencia",
    "Inside the gallery": "Dentro de la galería",
    "At the rural art studio": "En el estudio rural",
    "Choose your technique": "Elige tu técnica",
    "Gallery techniques": "Técnicas en la galería",
    "Studio techniques": "Técnicas en el estudio",
    "Reserve directly": "Reservar directamente",
    "What happens after you message us": "Qué sucede después de escribirnos",
    "Why does an art gallery carry the name of a nomadic tribe?": "¿Por qué una galería de arte lleva el nombre de un pueblo nómada?",
    "A story about migration, memory, family and art in San Miguel de Allende.": "Una historia sobre migración, memoria, familia y arte en San Miguel de Allende.",
    "Today, we know them as the Coahuiltecans.": "Hoy los conocemos como los coahuiltecos.",
    "We left northern Mexico behind.": "Dejamos atrás el norte de México.",
    "We brought our tools. Our drawings. Our paintings. Our memories.": "Trajimos nuestras herramientas, nuestros dibujos, nuestras pinturas y nuestros recuerdos.",
    "And we arrived in San Miguel de Allende.": "Y llegamos a San Miguel de Allende.",
    "Family. Craft. The need to create.": "La familia. El oficio. La necesidad de crear.",
    "Continue the journey": "Continúa el recorrido",
    "Discover the artwork": "Descubre la obra",
    "Visit the gallery": "Visita la galería",
    "Original Art in San Miguel de Allende": "Arte original en San Miguel de Allende",
    "A working gallery in San Miguel de Allende presenting original paintings, drawings, ceramics, commissioned portraits and private art experiences by local artists.": "Una galería en activo en San Miguel de Allende que presenta pintura, dibujo, cerámica, retratos por encargo y experiencias artísticas privadas de artistas locales.",
    "Conceptual painting exploring movement and human presence.": "Pintura conceptual que explora el movimiento y la presencia humana.",
    "Drawing and painting focused on identity and the body.": "Dibujo y pintura centrados en la identidad y el cuerpo.",
    "Handmade ceramics designed for daily use and collecting.": "Cerámica hecha a mano para el uso cotidiano y el coleccionismo.",
    "Oil portraits created through a traditional Venetian technique, developed slowly through layered painting.": "Retratos al óleo realizados mediante una técnica veneciana tradicional, desarrollados lentamente por capas.",
    "Each portrait is created from photographic references and includes pencil studies as part of the process.": "Cada retrato se crea a partir de referencias fotográficas e incluye estudios a lápiz como parte del proceso.",
    "Only a limited number of portraits are accepted each year.": "Cada año se acepta un número limitado de retratos.",
    "Private art experiences inside a working gallery in San Miguel de Allende.": "Experiencias artísticas privadas dentro de una galería en activo en San Miguel de Allende.",
    "Paint your own Parroquia": "Pinta tu propia Parroquia",
    "Draw your partner": "Dibuja a tu pareja",
    "Watercolor, charcoal, acrylic": "Acuarela, carbón y acrílico",
    "Ask questions by WhatsApp or reserve instantly through Airbnb.": "Pregunta por WhatsApp o reserva al instante mediante Airbnb.",
    "Receive a complimentary printable artwork, plus occasional exhibition invitations and collector notes.": "Recibe una obra imprimible de cortesía, además de invitaciones ocasionales a exposiciones y notas para coleccionistas.",
    "Discover original painting, drawing, ceramics and commissioned portraiture from the artists of Galería Coahuilteca.": "Descubre pintura, dibujo, cerámica y retratos por encargo de los artistas de Galería Coahuilteca.",
    "Enter each artist’s catalogue or commission page to explore the work in greater depth.": "Entra al catálogo o página de encargos de cada artista para conocer su obra con mayor profundidad.",
    "Migration, movement and collective human presence through a graphic, highly recognizable pictorial language.": "Migración, movimiento y presencia humana colectiva mediante un lenguaje pictórico gráfico y reconocible.",
    "Original oil portraits developed through drawing, layered painting and close observation. Private commissions available.": "Retratos originales al óleo desarrollados mediante dibujo, pintura por capas y observación cercana. Encargos privados disponibles.",
    "A hand-built ceramic chess set populated by small character pieces, currently in development at the gallery.": "Un ajedrez de cerámica construido a mano con pequeñas piezas-personaje, actualmente en desarrollo en la galería.",
    "Send a photo and approximate wall dimensions. The gallery can prepare a personal selection of three works for your space.": "Envía una foto y las medidas aproximadas del muro. La galería puede preparar una selección personal de tres obras para tu espacio.",
    "A portrait made to outlive the photograph.": "Un retrato creado para trascender la fotografía.",
    "Commission an original oil portrait by Mexican artist Indhira. Each work is developed slowly through drawing, layered painting and careful observation, creating an image intended to hold presence, memory and character beyond a single photograph.": "Encarga un retrato original al óleo de la artista mexicana Indhira. Cada obra se desarrolla lentamente mediante dibujo, pintura por capas y observación cuidadosa para preservar presencia, memoria y carácter más allá de una sola fotografía.",
    "From photograph to painting.": "De la fotografía a la pintura.",
    "The commission is built as a work of art, not as a photographic copy. Indhira begins by selecting the strongest references, studies the structure of the face, develops the drawing and gradually builds the painting through multiple layers.": "El encargo se construye como una obra de arte, no como una copia fotográfica. Indhira selecciona las mejores referencias, estudia la estructura del rostro, desarrolla el dibujo y construye gradualmente la pintura mediante múltiples capas.",
    "You share who the portrait is for, the feeling you want the work to carry and the space where it may live.": "Compartes para quién es el retrato, la emoción que deseas transmitir y el espacio donde vivirá la obra.",
    "The gallery helps select photographic references with the right light, expression and presence for the painting.": "La galería ayuda a seleccionar referencias fotográficas con la luz, expresión y presencia adecuadas.",
    "The portrait begins with structure, proportion and studies before the final painted layers are developed.": "El retrato comienza con estructura, proporción y estudios antes de desarrollar las capas finales de pintura.",
    "Color, depth and skin are built gradually through a slow layered process until the portrait reaches its final presence.": "El color, la profundidad y la piel se construyen gradualmente por capas hasta que el retrato alcanza su presencia final.",
    "Not simply a likeness. A painting meant to become part of a family’s visual history.": "No es sólo un parecido: es una pintura destinada a formar parte de la historia visual de una familia.",
    "Commission sizes.": "Formatos de encargo.",
    "Choose one of the standard formats below, or contact the gallery to discuss a different size, composition or number of figures.": "Elige uno de los formatos estándar o contacta a la galería para conversar sobre otras medidas, composiciones o número de figuras.",
    "Intimate portrait": "Retrato íntimo",
    "Ideal for one figure.": "Ideal para una figura.",
    "Approx. 3 months": "Aprox. 3 meses",
    "Collector portrait": "Retrato de colección",
    "A larger portrait with greater scale and presence.": "Un retrato de mayor formato, escala y presencia.",
    "Approx. 6 months": "Aprox. 6 meses",
    "Bespoke portrait": "Retrato personalizado",
    "Other dimensions, compositions or multiple figures.": "Otras dimensiones, composiciones o varias figuras.",
    "Format, timeline and price are determined personally with the artist before work begins.": "El formato, plazo y precio se acuerdan personalmente con la artista antes de comenzar.",
    "Price on request": "Precio bajo consulta",
    "What you receive.": "Qué recibirás.",
    "Each finished commission is delivered as an original artwork with gallery documentation and personal support for packing and shipping.": "Cada encargo terminado se entrega como obra original con documentación de la galería y apoyo personal para embalaje y envío.",
    "Original work": "Obra original",
    "An original oil portrait created specifically for the collector.": "Un retrato original al óleo creado especialmente para el coleccionista.",
    "Documentation": "Documentación",
    "Certificate of authenticity and complete technical information for the work.": "Certificado de autenticidad e información técnica completa de la obra.",
    "Private process": "Proceso privado",
    "Direct communication with the gallery throughout the commission.": "Comunicación directa con la galería durante todo el encargo.",
    "Professional packing and worldwide shipping options coordinated by the gallery.": "Embalaje profesional y opciones de envío mundial coordinadas por la galería.",
    "Begin with a photograph.": "Comienza con una fotografía.",
    "Figurative painting, drawing and portraiture exploring identity, memory and the female body.": "Pintura figurativa, dibujo y retrato que exploran identidad, memoria y cuerpo femenino.",
    "Explore Jacarandas or request a private oil portrait commission.": "Explora Jacarandas o solicita un retrato privado al óleo.",
    "A bilingual digital catalogue and downloadable printable artwork from Indhira’s Jacarandas series.": "Catálogo digital bilingüe y obra imprimible descargable de la serie Jacarandas de Indhira.",
    "Request a custom portrait developed in oil paint, created specifically for you or someone you love.": "Solicita un retrato personalizado al óleo, creado especialmente para ti o para alguien importante.",
    "How would you like to connect with the gallery?": "¿Cómo te gustaría comunicarte con la galería?",
    "Whether you are looking for a work to take home, considering a portrait commission or planning a private art experience, we are happy to assist personally.": "Ya sea que busques una obra, consideres encargar un retrato o planees una experiencia artística privada, con gusto te atenderemos personalmente.",
    "A working gallery located in the historic center of San Miguel de Allende.": "Una galería en activo ubicada en el centro histórico de San Miguel de Allende.",
    "Discover original paintings, drawings, ceramics, commissioned portraits and private art experiences in an intimate space where art is created and exhibited.": "Descubre pintura, dibujo, cerámica, retratos por encargo y experiencias artísticas privadas en un espacio íntimo donde el arte se crea y se exhibe.",
    "Ceramic Chess": "Ajedrez de cerámica",
    "The project is currently in development. The gallery is presenting selected studio images while the final set is completed.": "El proyecto está en desarrollo. La galería presenta imágenes seleccionadas del estudio mientras se completa el conjunto final.",
    "Studio process": "Proceso de estudio",
    "Details from the making process reveal the individual modeling, painting and character development behind the set.": "Los detalles del proceso revelan el modelado, la pintura y el desarrollo individual de los personajes del conjunto.",
    "Interested in the finished set?": "¿Te interesa el conjunto terminado?",
    "The ceramic chess set will be presented by the gallery once completed. You can ask to be contacted when final images, dimensions and price are available.": "La galería presentará el ajedrez de cerámica cuando esté terminado. Puedes solicitar que te contactemos cuando estén disponibles las imágenes finales, las dimensiones y el precio.",
    "Home": "Inicio",
    "Shop": "Tienda",
    "Portraits": "Retratos",
    "Experiences": "Experiencias",
    "Cultural agenda": "Agenda cultural",
    "Visit": "Visita",
    "Contact": "Contacto",
    "Available artwork": "Obra disponible",
    "Worldwide shipping": "Envíos a todo el mundo",
    "Artists & work": "Artistas y obra",
    "Explore portfolio →": "Explorar portafolio →",
    "Visit Instagram →": "Visitar Instagram →",
    "COMMISSIONED WORK": "OBRA POR ENCARGO",
    "Portrait Commissions": "Retratos por encargo",
    "by Indhira pintora": "por Indhira pintora",
    "Explore more →": "Explorar más →",
    "Request a Portrait": "Solicitar un retrato",
    "Create inside a working gallery": "Crea dentro de una galería en activo",
    "Ask by WhatsApp": "Preguntar por WhatsApp",
    "Book on Airbnb": "Reservar en Airbnb",
    "Visit us": "Visítanos",
    "Get Directions": "Cómo llegar",
    "Subscribe to our newsletter": "Suscríbete a nuestro boletín",
    "Collect something original.": "Colecciona algo original.",
    "Artists & collections": "Artistas y colecciones",
    "View catalogue →": "Ver catálogo →",
    "Commission a portrait →": "Encargar un retrato →",
    "Preview project →": "Ver proyecto →",
    "Coming soon": "Próximamente",
    "Prefer a private edit?": "¿Prefieres una selección privada?",
    "Request private edit": "Solicitar selección privada",
    "Choose how to connect": "Elige cómo conectar",
    "Printable collection": "Colección imprimible",
    "Open Jacarandas shop": "Abrir tienda Jacarandas",
    "Private commission": "Encargo privado",
    "Oil portrait": "Retrato al óleo",
    "View portrait commissions": "Ver retratos por encargo",
    "Portrait commissions": "Retratos por encargo",
    "Request your portrait": "Solicita tu retrato",
    "The process": "El proceso",
    "Selected works": "Obras seleccionadas",
    "Frequently asked questions": "Preguntas frecuentes",
    "Start your commission": "Inicia tu encargo",
    "Contact the artist": "Contactar a la artista",
    "Jacarandas digital shop": "Tienda digital Jacarandas",
    "Complete collection": "Colección completa",
    "Printable artwork": "Obra imprimible",
    "Purchase / Comprar": "Comprar / Purchase",
    "Secure payment": "Pago seguro",
    "Immediate delivery": "Entrega inmediata",
    "Personal use": "Uso personal",
    "About the experience": "Sobre la experiencia",
    "Reserve your experience": "Reserva tu experiencia",
    "Gallery or studio": "Galería o estudio",
    "Cultural agenda in San Miguel de Allende": "Agenda cultural en San Miguel de Allende",
    "Plan your visit": "Planea tu visita",
    "Opening hours": "Horario",
    "Location": "Ubicación",
    "Send us a message": "Envíanos un mensaje",
    "Listen to our story": "Escucha nuestra historia",
    "English": "Inglés",
    "Spanish": "Español",
    "Back to top": "Volver arriba",
    "← Back to shop": "← Volver a la tienda",
    "Portrait commissions · Indhira": "Retratos por encargo · Indhira",
    "View artist profile →": "Ver perfil de la artista →",
    "Original oil painting": "Pintura original al óleo",
    "Traditional layered process": "Proceso tradicional por capas",
    "Certificate of authenticity": "Certificado de autenticidad",
    "Collect": "Colecciona",
    "something original.": "algo original.",
    "Original work · Private assistance · Worldwide shipping": "Obra original · Atención privada · Envíos a todo el mundo",
    "01 · PAINTING": "01 · PINTURA",
    "02 · PORTRAIT COMMISSIONS": "02 · RETRATOS POR ENCARGO",
    "03 · CERAMICS": "03 · CERÁMICA",
    "PAINTING": "PINTURA",
    "PORTRAIT COMMISSIONS": "RETRATOS POR ENCARGO",
    "CERAMICS": "CERÁMICA",
    "Working gallery · San Miguel de Allende": "Galería en activo · San Miguel de Allende",
    "WORKING GALLERY · SAN MIGUEL DE ALLENDE": "GALERÍA EN ACTIVO · SAN MIGUEL DE ALLENDE"
  };

  /* AUDIT_COMPLETE_TRANSLATIONS */
  Object.assign(dictionary, {
  "· Worldwide shipping ·": "· Envíos a todo el mundo ·",
  "A gift from the gallery": "Un regalo de la galería",
  "Collectors · Press · Commissions · Private appointments": "Coleccionistas · Prensa · Encargos · Citas privadas",
  "Limited commissions each year · Worldwide shipping · Private guidance from the gallery": "Encargos limitados cada año · Envíos a todo el mundo · Atención privada de la galería",
  "Conversation": "Conversación",
  "References": "Referencias",
  "Drawing": "Dibujo",
  "Painting": "Pintura",
  "DEVELOPING THE IMAGE": "DESARROLLO DE LA IMAGEN",
  "AN EARLIER STAGE": "UNA ETAPA ANTERIOR",
  "50% deposit to begin": "50% de anticipo para comenzar",
  "50% before delivery": "50% antes de la entrega",
  "Painted detail · Layer, color and gesture": "Detalle pictórico · Capa, color y gesto",
  "The artist at work · San Miguel de Allende": "La artista trabajando · San Miguel de Allende",
  "Delivery": "Entrega",
  "Send the gallery one or two reference images and the approximate size you are considering. If you are in San Miguel de Allende, Indhira can also photograph you personally for the portrait once the commission is confirmed. We will guide you through each step personally.": "Envía a la galería una o dos imágenes de referencia y el tamaño aproximado que estás considerando. Si estás en San Miguel de Allende, Indhira también puede fotografiarte personalmente una vez confirmado el encargo. Te guiaremos personalmente en cada paso.",
  "Explore more work from Galería Coahuilteca": "Explora más obra de Galería Coahuilteca",
  "Portrait commissions by Indhira": "Retratos por encargo de Indhira",
  "Art Experiences": "Experiencias artísticas",
  "Paint & Wine": "Pintura y vino",
  "1 participant": "1 participante",
  "2 participants": "2 participantes",
  "3 participants": "3 participantes",
  "4 participants": "4 participantes",
  "Private group rate · 15% group discount": "Tarifa de grupo privado · 15% de descuento grupal",
  "15% group discount": "15% de descuento grupal",
  "Best group rate · 25% group discount": "Mejor tarifa grupal · 25% de descuento",
  "Airbnb prices may vary slightly by date. USD amounts are approximate and update daily using an institutional reference exchange rate.": "Los precios de Airbnb pueden variar ligeramente según la fecha. Los importes en USD son aproximados y se actualizan diariamente con un tipo de cambio institucional de referencia.",
  "All materials are included, along with step-by-step guidance by a professional local artist with over 20 years of experience. Accompanied by Chiapas coffee and a curated selection of light refreshments. Each participant completes and takes home their own artwork, and also receives a small original piece from the gallery, presented in a custom Galería Coahuilteca tote bag.": "Todos los materiales están incluidos, junto con la guía paso a paso de una artista local profesional con más de 20 años de experiencia. Se acompaña con café de Chiapas y una selección de refrigerios ligeros. Cada participante termina y se lleva su propia obra, además de recibir una pequeña pieza original de la galería en una bolsa de Galería Coahuilteca.",
  "Most drawing and painting sessions take place inside Galería Coahuilteca, in the historic center of San Miguel de Allende.": "La mayoría de las sesiones de dibujo y pintura se realizan dentro de Galería Coahuilteca, en el centro histórico de San Miguel de Allende.",
  "Best for graphite, watercolor, charcoal, acrylic, oil pastels, soft pastels and clean mixed media.": "Ideal para grafito, acuarela, carbón, acrílico, pastel al óleo, pastel seco y técnicas mixtas limpias.",
  "Central, easy, walkable and ideal for visitors who want a beautiful creative experience without leaving downtown.": "Céntrica, accesible a pie e ideal para visitantes que desean una bella experiencia creativa sin salir del centro.",
  "Get directions": "Cómo llegar",
  "Open gallery map →": "Abrir mapa de la galería →",
  "Messier and more material-based techniques take place at the private studio in Corralejo de Arriba, a rural community about 15 minutes from the gallery and del centro de San Miguel.": "Las técnicas con más materiales se realizan en el estudio privado de Corralejo de Arriba, una comunidad rural a unos 15 minutos de la galería y del centro de San Miguel.",
  "Messier and more material-based techniques take place at the private studio in Corralejo de Arriba, a rural community about 15 minutes from the gallery and downtown San Miguel.": "Las técnicas con más materiales se realizan en el estudio privado de Corralejo de Arriba, una comunidad rural a unos 15 minutos de la galería y del centro de San Miguel.",
  "Best for oil painting, ceramics and printmaking. This option offers a slower, deeper and more immersive artistic experience surrounded by a quieter landscape.": "Ideal para óleo, cerámica y grabado. Esta opción ofrece una experiencia artística más pausada, profunda e inmersiva en un paisaje tranquilo.",
  "Transportation is not included, but the location opens easily in Google Maps.": "El transporte no está incluido, pero la ubicación se abre fácilmente en Google Maps.",
  "Open studio map →": "Abrir mapa del estudio →",
  "Graphite": "Grafito",
  "Charcoal": "Carbón",
  "Watercolor": "Acuarela",
  "Acrylic": "Acrílico",
  "Oil pastels": "Pastel al óleo",
  "Soft pastels": "Pastel seco",
  "Clean mixed media": "Técnicas mixtas limpias",
  "Oil painting": "Pintura al óleo",
  "Ceramics": "Cerámica",
  "Printmaking": "Grabado",
  "Longer material-based processes": "Procesos de materiales más prolongados",
  "Booking": "Reservaciones",
  "You can book through Airbnb, or request a custom private session directly with Galería Coahuilteca by WhatsApp. For direct inquiries, send your preferred date, time, number of guests and chosen experience.": "Puedes reservar mediante Airbnb o solicitar por WhatsApp una sesión privada personalizada directamente con Galería Coahuilteca. Envía la fecha, hora, número de participantes y experiencia elegida.",
  "Best option for gallery sessions. Airbnb bookings are available only for experiences held at Galería Coahuilteca.": "La mejor opción para sesiones en la galería. Las reservas de Airbnb están disponibles únicamente para experiencias realizadas en Galería Coahuilteca.",
  "For rural studio sessions — including pouring, ceramics, printmaking and oil painting — please contact us directly to confirm available dates.": "Para sesiones en el estudio rural —incluidos pouring, cerámica, grabado y óleo— contáctanos directamente para confirmar fechas disponibles.",
  "The same participant prices apply.": "Se aplican los mismos precios por participante.",
  "Open Airbnb": "Abrir Airbnb",
  "Choose this option for rural studio sessions, custom dates, private groups, couples or families.": "Elige esta opción para sesiones en el estudio rural, fechas personalizadas, grupos privados, parejas o familias.",
  "Studio techniques include pouring, ceramics, printmaking and oil painting. The same participant prices apply; availability must be confirmed directly with the gallery.": "Las técnicas de estudio incluyen pouring, cerámica, grabado y óleo. Se aplican los mismos precios por participante; la disponibilidad debe confirmarse directamente con la galería.",
  "We will send available times, prices and payment options. For direct reservations, PayPal is recommended for international visitors and bank transfer for clients in Mexico. Airbnb remains available for guests who prefer platform booking.": "Enviaremos horarios disponibles, precios y opciones de pago. Para reservas directas recomendamos PayPal a visitantes internacionales y transferencia bancaria a clientes en México. Airbnb sigue disponible para quienes prefieren reservar en la plataforma.",
  "Art Gallery": "Galería de arte",
  "Hours": "Horario",
  "Open daily": "Abierto todos los días",
  "Available artwork · Reservations · Commissions": "Obra disponible · Reservaciones · Encargos",
  "Email": "Correo electrónico",
  "Available Works · Galería Coahuilteca": "Obra disponible · Galería Coahuilteca",
  "Original paintings exploring migration, movement and collective human presence. Prices and dimensions appear on each catalogue sheet.": "Pinturas originales que exploran la migración, el movimiento y la presencia humana colectiva. Los precios y medidas aparecen en cada ficha del catálogo.",
  "Original work · San Miguel de Allende · Mexico & USA shipping · International quotes available": "Obra original · San Miguel de Allende · Envíos a México y EE. UU. · Cotizaciones internacionales disponibles",
  "53 works available in catalogue": "53 obras disponibles en el catálogo",
  "Shipping is shown with each work. Canvas works are carefully protected and shipped rolled, without wooden stretcher bars. Works on cotton paper are shipped carefully protected. Other destinations, stretched-canvas shipping and framed shipping are quoted individually.": "El envío se indica en cada obra. Los lienzos se protegen y envían enrollados, sin bastidor. Las obras sobre papel de algodón se envían protegidas. Otros destinos y los envíos con bastidor o marco se cotizan individualmente.",
  "Looking for something made for your space?": "¿Buscas una obra creada para tu espacio?",
  "Fermigrante can create an original work in custom dimensions and a color palette selected for your space. Tell us the size and colors you have in mind.": "Fermigrante puede crear una obra original en medidas especiales y con una paleta elegida para tu espacio. Cuéntanos qué tamaño y colores tienes en mente.",
  "Request a custom work": "Solicitar una obra personalizada",
  "Need assistance?": "¿Necesitas ayuda?",
  "Send the gallery the work reference and your destination. We will confirm availability, final shipping and payment options.": "Envía a la galería la referencia de la obra y tu destino. Confirmaremos disponibilidad, envío final y opciones de pago.",
  "Contact the gallery": "Contactar a la galería",
  "Fermigrante · Available works": "Fermigrante · Obras disponibles",
  "Edd · Ceramic Chess · Preview": "Edd · Ajedrez de cerámica · Avance",
  "Galería Coahuilteca · Ceramics": "Galería Coahuilteca · Cerámica",
  "Ceramic Chess — a hand-built chess set composed of individually modeled characters. Each figure is made by hand, giving the set the character of a small sculptural world rather than a conventional game object.": "Ajedrez de cerámica: un conjunto construido a mano con personajes modelados individualmente. Cada figura está hecha a mano, lo que le da el carácter de un pequeño mundo escultórico.",
  "Hand-built ceramic · Unique project · San Miguel de Allende": "Cerámica hecha a mano · Proyecto único · San Miguel de Allende",
  "Ceramic Chess · Work in progress": "Ajedrez de cerámica · Obra en proceso",
  "Hand-modeled characters": "Personajes modelados a mano",
  "Individually modeled pieces": "Piezas modeladas individualmente",
  "Notify me": "Avísame",
  "Edd · Ceramic Chess · Coming soon": "Edd · Ajedrez de cerámica · Próximamente",
  "Indhira · Printable collection": "Indhira · Colección imprimible",
  "A collection about women, memory, resistance and presence. Discover the complete bilingual catalogue or collect an individual printable artwork.": "Una colección sobre mujeres, memoria, resistencia y presencia. Descubre el catálogo bilingüe completo o adquiere una obra imprimible individual.",
  "High-resolution digital files for personal printing. Secure purchase and immediate digital delivery after payment.": "Archivos digitales de alta resolución para impresión personal. Compra segura y entrega digital inmediata después del pago.",
  "Jacarandas — Bilingual catalogue": "Jacarandas — Catálogo bilingüe",
  "Complete bilingual digital catalogue of the Jacarandas series.": "Catálogo digital bilingüe con la serie completa Jacarandas.",
  "Digital PDF": "PDF digital",
  "English + Español": "Inglés + Español",
  "Secure payment processed by Gumroad · Immediate download": "Pago seguro procesado por Gumroad · Descarga inmediata",
  "Printable artwork · 01": "Obra imprimible · 01",
  "Printable artwork · 02": "Obra imprimible · 02",
  "Printable artwork · 03": "Obra imprimible · 03",
  "Printable artwork · 04": "Obra imprimible · 04",
  "Printable artwork · 05": "Obra imprimible · 05",
  "Printable artwork · 06": "Obra imprimible · 06",
  "Printable artwork · 07": "Obra imprimible · 07",
  "Printable artwork · 08": "Obra imprimible · 08",
  "Printable artwork · 09": "Obra imprimible · 09",
  "Printable artwork · 10": "Obra imprimible · 10",
  "Printable artwork · 11": "Obra imprimible · 11",
  "Printable artwork · 12": "Obra imprimible · 12",
  "Printable artwork · 13": "Obra imprimible · 13",
  "Printable artwork · 14": "Obra imprimible · 14",
  "Printable artwork · 15": "Obra imprimible · 15",
  "Printable artwork · 16": "Obra imprimible · 16",
  "Printable artwork · 17": "Obra imprimible · 17",
  "Printable artwork · 18": "Obra imprimible · 18",
  "Printable artwork · 19": "Obra imprimible · 19",
  "Woman Facing the Wall — high-resolution printable artwork.": "Mujer frente al muro — obra imprimible de alta resolución.",
  "Printable PDF": "PDF imprimible",
  "High resolution": "Alta resolución",
  "Young Woman at the Barricade — high-resolution printable artwork.": "Joven frente a la barricada — obra imprimible de alta resolución.",
  "Free — high-resolution printable artwork from Jacarandas.": "Libres — obra imprimible de alta resolución de Jacarandas.",
  "Collective Embrace — high-resolution printable artwork.": "Abrazo colectivo — obra imprimible de alta resolución.",
  "To Be Free or Not to Be — high-resolution printable artwork.": "Ser libre o no ser — obra imprimible de alta resolución.",
  "Long Live the Vulva — feminism, equality and freedom.": "Viva la vulva — feminismo, igualdad y libertad.",
  "Women Raising Their Voices — high-resolution printable artwork.": "Mujeres alzando la voz — obra imprimible de alta resolución.",
  "Not One Woman Less — high-resolution printable artwork.": "Ni una menos — obra imprimible de alta resolución.",
  "The Future Is Female": "El futuro es femenino",
  "A high-resolution printable artwork from the Jacarandas series.": "Obra imprimible de alta resolución de la serie Jacarandas.",
  "Digital products are for personal use only. Due to the nature of downloadable files, purchases are final. Los precios en pesos son aproximados; el importe final dependerá del tipo de cambio aplicado durante el pago.": "Los productos digitales son sólo para uso personal. Por la naturaleza de los archivos descargables, las compras son definitivas. Los precios en pesos son aproximados; el importe final dependerá del tipo de cambio aplicado durante el pago.",
  "Printable art · Secure payment · Immediate delivery": "Arte imprimible · Pago seguro · Entrega inmediata",
  "Artist · Galería Coahuilteca": "Artista · Galería Coahuilteca",
  "Worldwide shipping · Private commissions": "Envíos a todo el mundo · Encargos privados",
  "The story behind our name": "La historia detrás de nuestro nombre",
  "Listen to the story": "Escucha la historia",
  "Audio in English": "Audio en inglés",
  "Long before states existed. Long before borders existed. Long before there were maps.": "Mucho antes de que existieran los estados. Mucho antes de que existieran las fronteras. Mucho antes de que hubiera mapas.",
  "Small human groups moved through the territories we now call Coahuila, Nuevo León, Tamaulipas and South Texas.": "Pequeños grupos humanos recorrían los territorios que hoy llamamos Coahuila, Nuevo León, Tamaulipas y el sur de Texas.",
  "Their history traveled with them. It lived in memory. In stories. In people.": "Su historia viajaba con ellos. Vivía en la memoria. En los relatos. En las personas.",
  "When the time came to name this gallery, we thought of those ancient travelers.": "Cuando llegó el momento de nombrar esta galería, pensamos en aquellos antiguos viajeros.",
  "Perhaps because we, too, had begun our own journey. We had changed cities, built a new life and learned to look at a different landscape.": "Quizá porque nosotros también habíamos comenzado nuestro propio viaje. Habíamos cambiado de ciudad, construido una nueva vida y aprendido a mirar un paisaje distinto.",
  "Yet something remained intact.": "Sin embargo, algo permaneció intacto.",
  "Galería Coahuilteca was born from that experience. From understanding that one can travel great distances and still preserve what gives them identity.": "Galería Coahuilteca nació de esa experiencia: de comprender que podemos recorrer grandes distancias y conservar aquello que nos da identidad.",
  "Because memory also travels. And some stories find new ways to keep being told.": "Porque la memoria también viaja. Y algunas historias encuentran nuevas maneras de seguir siendo contadas.",
  "Now that you know the origin of our name, we invite you to discover the artwork, visit the gallery or write to us.": "Ahora que conoces el origen de nuestro nombre, te invitamos a descubrir la obra, visitar la galería o escribirnos.",
  "Write to us": "Escríbenos",
  "Private gallery list": "Lista privada de la galería",
  "Stay close": "Mantente cerca",
  "to the art": "del arte",
  "Receive exhibition invitations and important news from Galería Coahuilteca.": "Recibe invitaciones a exposiciones y noticias importantes de Galería Coahuilteca.",
  "Email address": "Correo electrónico",
  "Subscribe": "Suscribirme",
  "Continue with WhatsApp": "Continuar por WhatsApp",
  "Choose one option. Occasional messages only. You can unsubscribe at any time.": "Elige una opción. Sólo enviaremos mensajes ocasionales. Puedes cancelar tu suscripción en cualquier momento.",
  "Visit the gallery website →": "Visitar el sitio de la galería →"
});

  const originals = new WeakMap();

  function translateTextNode(node, language) {
    if (!originals.has(node)) originals.set(node, node.nodeValue);
    const original = originals.get(node);
    if (language === "en") {
      node.nodeValue = original;
      return;
    }
    const trimmed = original.trim().replace(/\s+/g, " ");
    const translated = dictionary[trimmed];
    if (!translated) return;
    const leading = original.match(/^\s*/)[0];
    const trailing = original.match(/\s*$/)[0];
    node.nodeValue = leading + translated + trailing;
  }

  function applyLanguage(language) {
    document.documentElement.lang = language;
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
      acceptNode(node) {
        const parent = node.parentElement;
        if (!parent || /^(SCRIPT|STYLE|NOSCRIPT)$/.test(parent.tagName)) return NodeFilter.FILTER_REJECT;
        return node.nodeValue.trim() ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
      }
    });
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(node => translateTextNode(node, language));
    document.querySelectorAll(".gc-language-button").forEach(button => {
      const active = button.dataset.language === language;
      button.classList.toggle("is-active", active);
      button.setAttribute("aria-pressed", String(active));
    });
    try { localStorage.setItem(STORAGE_KEY, language); } catch (error) {}
  }

  function buildSelector() {
    if (document.querySelector(".gc-language-switch")) return;
    const host = document.querySelector("header nav") || document.body;
    const selector = document.createElement("div");
    selector.className = "gc-language-switch";
    selector.classList.add(host.tagName === "NAV" ? "gc-language-under-menu" : "gc-language-floating");
    selector.setAttribute("aria-label", "Idioma / Language");
    selector.innerHTML = '<button type="button" class="gc-language-button" data-language="es">ES</button><span aria-hidden="true">/</span><button type="button" class="gc-language-button" data-language="en">EN</button>';
    host.appendChild(selector);
    selector.querySelectorAll("button").forEach(button => {
      button.addEventListener("click", () => applyLanguage(button.dataset.language));
    });
  }

  const style = document.createElement("style");
  style.textContent = '.gc-language-switch{display:flex;align-items:center;gap:6px;font:700 11px/1 Arial,sans-serif;letter-spacing:.12em;color:#555;white-space:nowrap;z-index:1001}.gc-language-under-menu{position:absolute;right:0;top:calc(100% + 9px);padding:5px 0}.gc-language-floating{position:fixed;right:20px;top:20px;padding:10px 12px;background:rgba(255,255,255,.94);border:1px solid rgba(0,0,0,.12);border-radius:999px;box-shadow:0 6px 20px rgba(0,0,0,.10);backdrop-filter:blur(8px)}.gc-language-button{border:0;background:transparent;color:inherit;padding:6px 2px;cursor:pointer;opacity:.45}.gc-language-button.is-active{opacity:1;text-decoration:underline;text-underline-offset:4px}@media(max-width:800px){.gc-language-floating{right:14px;bottom:14px;padding:9px 11px}}';
  document.head.appendChild(style);
  const nav = document.querySelector("header nav");
  if (nav) nav.style.position = "relative";

  function start() {
    buildSelector();
    let language = "";
    try { language = localStorage.getItem(STORAGE_KEY) || ""; } catch (error) {}
    if (!language) language = navigator.language.toLowerCase().startsWith("es") ? "es" : "en";
    applyLanguage(language);
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", start);
  else start();
})();
